/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberog5.vistas;

import bomberog5.accesoDatos.BrigadaData;
import bomberog5.accesoDatos.Conexion;
import bomberog5.accesoDatos.SiniestroData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaco
 */
public class ResolucionSiniestrosView extends javax.swing.JInternalFrame {

    private BrigadaData briga = new BrigadaData();
    private SiniestroData sin = new SiniestroData();
    private Connection con = null;
    private DefaultTableModel SinAct = new DefaultTableModel();
    private DefaultTableModel SinFin = new DefaultTableModel();

    /**
     * Creates new form ResolucionSiniestrosView
     */
    public ResolucionSiniestrosView() {
        initComponents();
        con = Conexion.getConexion();
        llenarTablaSiniestrosActivos();
        llenarTablaSiniestrosFinalizados();
        llenarComboPuntuacion();

//        cabeceraSiniestroActivos();
//        cabeceraSiniestroFinalizados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTSinAct1 = new javax.swing.JTable();
        jDFechaResol = new com.toedter.calendar.JDateChooser();
        jCPuntos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTHoraRes = new javax.swing.JTextField();
        jTMinResol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBFinSin = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTSinFin = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();

        jLabel1.setText("Siniestros Activos");

        jTSinAct1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTSinAct1);

        jLabel2.setText(":");

        jLabel3.setText("Hora ");

        jLabel4.setText("Puntuación");

        jLabel5.setText("Fecha");

        jBFinSin.setText("Finalizar Siniestro");
        jBFinSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinSinActionPerformed(evt);
            }
        });

        jTSinFin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTSinFin);

        jLabel6.setText("Siniestros Finalizados");

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDFechaResol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTHoraRes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTMinResol, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCPuntos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addComponent(jBFinSin)))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDFechaResol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTHoraRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTMinResol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jBFinSin)))
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBFinSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinSinActionPerformed
        actualizarSiniestroSeleccionado();
        llenarTablaSiniestrosActivos();
        llenarTablaSiniestrosFinalizados();
    }//GEN-LAST:event_jBFinSinActionPerformed

    public void llenarTablaSiniestrosActivos() {
        DefaultTableModel tSin = new DefaultTableModel();
        tSin.addColumn("ID");
        tSin.addColumn("Tipo");
        tSin.addColumn("Fecha");
        tSin.addColumn("Hora");
        //tSin.addColumn("CoordX");
        //tSin.addColumn("CoordY");
        tSin.addColumn("Detalles");
        jTSinAct1.setModel(tSin);

        try {

            String consulta = "SELECT idCodigo, tipo, fechaSiniestro, horaSiniestro, detalles FROM siniestro WHERE estadoS=1 AND idBrigada IS NOT NULL";
            PreparedStatement ps = con.prepareStatement(consulta);
            ResultSet rs = ps.executeQuery();
            SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");

            while (rs.next()) {
                Object[] fila = {
                    rs.getString("idCodigo"),
                    rs.getString("tipo"),
                    fecha.format(rs.getDate("fechaSiniestro")),
                    rs.getTime("horaSiniestro"),
                   // rs.getInt("coordx"),
                   // rs.getInt("coordY"),
                    rs.getString("detalles")

                };
                tSin.addRow(fila);
            }

        } catch (Exception e) {
            e.printStackTrace();
            // Manejar la excepción según tus necesidades
        }
    }

//    private void cabeceraSiniestroActivos() {
//        SinAct.addColumn("Tipo");
//        SinAct.addColumn("Fecha Siniestro");
//        SinAct.addColumn("Hora Siniestro");
//        SinAct.addColumn("Latitud");
//        SinAct.addColumn("Longitud");
//        SinAct.addColumn("Detalles");
//        jTSinAct1.setModel(SinAct);
//    }
    public void llenarTablaSiniestrosFinalizados() {
        DefaultTableModel tSinFin = new DefaultTableModel();
        tSinFin.addColumn("ID");
        tSinFin.addColumn("Tipo");
        tSinFin.addColumn("Fecha Resolucion");
        tSinFin.addColumn("Hora Resolucion");
        tSinFin.addColumn("Puntuación");

        jTSinFin.setModel(tSinFin);

        try {

            String consulta = "SELECT idCodigo, tipo, fechaResol, horaResol, detalles, puntuacion FROM siniestro WHERE estadoS=0";
            PreparedStatement ps = con.prepareStatement(consulta);
            ResultSet rs = ps.executeQuery();
            SimpleDateFormat fecha1 = new SimpleDateFormat("dd/MM/yyyy");

            while (rs.next()) {
                Object[] fila = {
                    rs.getString("idCodigo"),
                    rs.getString("tipo"),
                    fecha1.format(rs.getDate("fechaResol")), 
                    rs.getDate("fechaResol"),
                    rs.getTime("horaResol"),
                    rs.getInt("puntuacion"),
                    rs.getString("detalles")

                };
                tSinFin.addRow(fila);
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    private void llenarComboPuntuacion() {
        String[] puntuacion = sin.Puntuacion();
        jCPuntos.setModel(new javax.swing.DefaultComboBoxModel<>(puntuacion));
    }

//    private void cabeceraSiniestroFinalizados() {
//        SinFin.addColumn("Tipo");
//        SinFin.addColumn("Fecha Resolucion");
//        SinFin.addColumn("Hora Resolucion");
//        SinFin.addColumn("Detalles");
//        SinFin.addColumn("Puntuacion");
//        jTSinFin.setModel(SinFin);
//    }
    private void actualizarSiniestroSeleccionado() {
        int filaSeleccionada = jTSinAct1.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idCodigo = Integer.parseInt(jTSinAct1.getValueAt(filaSeleccionada, 0).toString());
            String consulta = "UPDATE siniestro SET fechaResol = ?, horaResol = ?, puntuacion = ?, estadoS = ? WHERE idCodigo = ?";

            try {
                PreparedStatement ps = con.prepareStatement(consulta);
                java.sql.Date fechaResol = new java.sql.Date(jDFechaResol.getDate().getTime());
                LocalTime localTime = LocalTime.of(
                        Integer.parseInt(jTHoraRes.getText()),
                        Integer.parseInt(jTMinResol.getText()));
                java.sql.Time horaResol = java.sql.Time.valueOf(localTime);
//                java.sql.Time horaResol = java.sql.Time.valueOf(jTHoraRes.getText() + ":" + jTMinResol.getText());                
                int puntuacion = Integer.parseInt(jCPuntos.getSelectedItem().toString());

                ps.setDate(1, fechaResol);
                ps.setTime(2, horaResol);
                ps.setInt(3, puntuacion);
                ps.setInt(4, 0);
                ps.setInt(5, idCodigo);

                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Siniestro finalizado");

                //String consultaObtenerIdBrigada = "SELECT idBrigada FROM siniestro WHERE idCodigo = ?";
                String consultaBrig = "UPDATE brigada SET estadoBr = 1 WHERE idBrigada = (SELECT idBrigada FROM siniestro WHERE idCodigo = ?)";

                
                PreparedStatement psBrigada = con.prepareStatement(consultaBrig);
                psBrigada.setInt(1, idCodigo);
                psBrigada.executeUpdate();

            } catch (Exception e) {
                e.printStackTrace();
                // Manejar la excepción según tus necesidades
            }

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFinSin;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCPuntos;
    private com.toedter.calendar.JDateChooser jDFechaResol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTHoraRes;
    private javax.swing.JTextField jTMinResol;
    private javax.swing.JTable jTSinAct1;
    private javax.swing.JTable jTSinFin;
    // End of variables declaration//GEN-END:variables
}
